### ISSUE TITLE
Connection to Hassio

### ISSUE THREAD

**Issue by mcfarlde** [korylprince/hassio-node-red#1]
Hello, I get an error about the connection to Hassio.  
"Connection error occured with the home-assistant server: {"type":"error","status":404}"
I've tried the IP address of my PI3 and the duckdns.org address with no success.  I can get to the the node-red web ui and have added a couple of node successfully, but after deployment, I get the error.  Are any dependencies required?  All I did was install your add-on.

**Comment by korylprince** [comment]
@mcfarlde did you see the [Node-RED Configuration part of the README](https://github.com/korylprince/hassio-node-red/tree/master/node-red#node-red-configuration)?: 

You should use `http://homeassistant:8123` (or `https://homeassistant:8123` if using SSL) from Node-RED to connect to Home Assistant. Example:

![image](https://user-images.githubusercontent.com/559762/34452555-b3b25886-ed07-11e7-919d-e88bf82dec95.png)

That's not a variable or anything; actually use "homeassistant". That's the hostname Hass.io plugins use to communicate with Home Assistant.

**Comment by mcfarlde** [comment]
Thank you very much, that has it working.
