### ISSUE TITLE
Home assistant connection failed with error: Connection to home assistant could not be established with config...

### ISSUE THREAD

**Issue by arnonel** [korylprince/hassio-node-red#10]
Please see https://community.home-assistant.io/t/cannot-install-node-red-node/43006/18

Getting this every second now: ""Home assistant connection failed with error: Connection to home assistant could not be established with config: ""

**Comment by korylprince** [comment]
From that thread, it looks like the issue corrected itself, so I'm going to close this issue.

For future issues, please consider posting to my add-on thread on the community: https://community.home-assistant.io/t/new-node-red-add-on/37068

(The thread you posted on was for the other Node-RED add-on, and I'm not following that one.)
