### ISSUE TITLE
Add-on causing error during install on Node-red 19.3

### ISSUE THREAD

**Issue by rlust** [korylprince/hassio-node-red#15]
Get the following errors when installing node:
 - node-red-contrib-home-assistant:server : SyntaxError: Unexpected identifier
10 Sep 22:33:01 - [info]  - node-red-contrib-home-assistant:server-events : SyntaxError: Unexpected identifier
10 Sep 22:33:01 - [info]  - node-red-contrib-home-assistant:server-state-changed : SyntaxError: Unexpected identifier
10 Sep 22:33:01 - [info]  - node-red-contrib-home-assistant:trigger-state : SyntaxError: Unexpected identifier
10 Sep 22:33:01 - [info]  - node-red-contrib-home-assistant:poll-state : SyntaxError: Unexpected identifier
10 Sep 22:33:01 - [info]  - node-red-contrib-home-assistant:api-call-service : SyntaxError: Unexpected identifier (line:2)
10 Sep 22:33:01 - [info]  - node-red-contrib-home-assistant:api-current-state : SyntaxError: Unexpected identifier (line:1)
10 Sep 22:33:01 - [info]  - node-red-contrib-home-assistant:api-get-history : SyntaxError: Unexpected identifier (line:2)
10 Sep 22:33:01 - [info]  - node-red-contrib-home-assistant:api-render-template : SyntaxError: Unexpected identifier (line:2)

**Comment by korylprince** [comment]
Sorry for the lack of a response. I've not had much time to work on this.

I've deprecated this add-on. Please see the [README](https://github.com/korylprince/hassio-node-red/tree/master/node-red) for instructions on migrating to a much better add-on.
