### ISSUE TITLE
can't install serial node

### ISSUE THREAD

**Issue by phil040462** [korylprince/hassio-node-red#17]
trying to install node-red-node-serialport group of nodes I get this error:
npm WARN deprecated bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes

> bcrypt@1.0.3 install /share/node-red/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v57-linux-arm64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@8.9.3 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/w...

can you hep?

**Comment by korylprince** [comment]
Sorry for the lack of a response. I've not had much time to work on this.

I've deprecated this add-on. Please see the [README](https://github.com/korylprince/hassio-node-red/tree/master/node-red) for instructions on migrating to a much better add-on.

**Comment by phil040462** [comment]
Thank you Kory.

cheers
Phil
