### ISSUE TITLE
Possible to use with base HASS install?

### ISSUE THREAD

**Issue by jmesberg** [korylprince/hassio-node-red#4]
Hi, I've compared the various Node-Red implementations out there and I think yours is very promising -- but I'm not a Hassio user, rather just base Hass on Python. Any chance you could provide guidance (or code) that would make this work? Thank you.

**Comment by korylprince** [comment]
This add-on is made to work with Hass.io. If you don't have Hass.io, then this add-on isn't going to be worth trying to get it to work.

If you already have docker, then there's an [official Node-RED](https://hub.docker.com/r/nodered/node-red-docker/) docker image you should use.

However, I'm guessing you're just running Home Assistant on Ubuntu or Raspbian. In that case, it's not that hard to just install Node-RED directly.

[Install Nodejs](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions):
```
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
```
Then install Node-RED:

```
mkdir ~/nodered
cd ~/nodered
npm install --production node-red
```
You can then start Node-RED with:

`~/nodered/node_modules/.bin/node-red`

and by default it will store your Node-RED files in `~/.node-red`.

As you can see though, this is all out of the scope of this project. If you want to install Node-RED and aren't using Hass.io, there's better tutorials than this out there. Ultimately, I really suggest you check out Hass.io as it makes things very easy to install.

**Comment by jmesberg** [comment]
Thank you very much for your quick reply. I found another project with all
of the needed pre-built nodes that works with a basic Hass install so I'm
good to go. Built several Node-RED automations already....good stuff. Good
luck with your project, and thanks again for your quick response.
