### ISSUE TITLE
Issue while migrating form notorious big node-red plugin

### ISSUE THREAD

**Issue by ashmodai6** [korylprince/hassio-node-red#5]
Hi,

I tried migrating from notorious big plugin to yours by just stopping the original plugin, install and start yours. It does start fine but none of the flow do work. 
extract of the logs..

29 Jan 17:22:35 - [info] Starting flows
29 Jan 17:22:35 - [error] [api-call-service:notify via telegram] JSON parse error in settings parser
29 Jan 17:22:35 - [error] [api-call-service:Service call] JSON parse error in settings parser
29 Jan 17:22:35 - [error] [api-call-service:notify via telegram] JSON parse error in settings parser
29 Jan 17:22:35 - [error] [api-call-service:notify via telegram] JSON parse error in settings parser
29 Jan 17:22:35 - [error] [api-call-service:Send command] JSON parse error in settings parser
29 Jan 17:22:35 - [error] [api-call-service:notify via telegram] JSON parse error in settings parser
29 Jan 17:22:35 - [info] Started flows
29 Jan 17:22:35 - [error] [server-state-changed:ether] Connection error occured with the home-assistant server: {"type":"error"}
...
29 Jan 17:22:35 - [error] [server-state-changed:Isis] Connection error occured with the home-assistant server: {"type":"error"}
29 Jan 17:22:35 - [info] [mqtt-broker:d12011b7.9336e] Connection failed to broker: node-red-client@mqtt://localhost:1883
....

Any idea where I could start to debug ?

**Comment by korylprince** [comment]
Please follow these steps:

1. Stop the add-on
2. move the existing node-red folder in /share
3. create a new, empty node-red folder /share
4. start the add-on
5. install the extra node-red modules your flows require
6. stop the add-on
7. copy the flows.json from the old folder to the new folder.
8. start the add-on
9. correct the Home Assistant nodes to use the [correct host name](https://github.com/korylprince/hassio-node-red/tree/master/node-red#node-red-configuration) and deploy the nodes
10. restart the add-on and see if there are still any errors in the log.

Note: it appears several of the errors in your log come from (I assume) a node-red telegram module, so if there's any extra configuration files, make sure they look right.

**Comment by ashmodai6** [comment]
Thanks a lot. I did and it was producing the same results. I was intrigued by your comment to use the correct host name so I checked my nodes configuration and I did see that I was using 127.0.0.1 or localhost. I changed these to the actually LAN IP address of my rpi3 running hassio and it worked. Now everything is fine ... I don't know why localhost was not working ?
Thanks a lot for your help and very quick support

PS:  I tried to update the node-red-contrib-home-assistant node to the latest 0.2.1 but it did not work with this error : "An update for this node is available, but it is not installed in a location that the palette manager can update." I assume this is because you integrated it into your package directly ?

**Comment by korylprince** [comment]
I've just added this as a clarification to the README. By "correct host name" I meant that you need to literally use "homeassistant" as the hostname for the Base URL in Node-RED.

I'm aware of the issues with updating the palette and I'm working on fixing this. I'm going to go ahead and close this issue since that's not related.
