### ISSUE TITLE
homekit pallet not installing in hassio? any idea

### ISSUE THREAD

**Issue by CroVlado** [korylprince/hassio-node-red#7]
run the install and it comes back with this error on gyp and mDNS then fails.

any help would be appreciated as im super novice at all of this still but trying to get my mqtt garage door linked back into home.app

23 Feb 15:55:02 - [info] Installing module: node-red-contrib-homekit, version: 0.2.1
23 Feb 15:55:36 - [warn] Installation of module node-red-contrib-homekit failed:
23 Feb 15:55:36 - [warn] ------------------------------------------
23 Feb 15:55:36 - [warn] 
> mdns@2.3.4 install /share/node-red/node_modules/mdns
> node-gyp rebuild
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.50
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /share/node-red/node_modules/mdns
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-23T20_55_36_615Z-debug.log
23 Feb 15:55:36 - [warn] ------------------------------------------

**Comment by CroVlado** [comment]
have the exact same issue.. hassio runs on python so i don't understand how its not finding a python executable.

**Comment by CroVlado** [comment]
it appears that it's looking for python 2 but hassio runs on python 3

**Comment by korylprince** [comment]
Python is not installed in the container image. NPM needs python to build that palette.

I would consider adding python to the image (I haven't yet because it would increase the size quite a bit), but the add-on doesn't appear to currently work in Docker. See the [README](https://github.com/mschm/node-red-contrib-homekit) Docker section.

So at this point I'm going to close this. Once they've got it working in Docker, then I might consider adding all of the dependencies (python, avahi, etc) to my add-on.
