### ISSUE TITLE
UPD Multicasting? (SONOS & XIAOMI not working)

### ISSUE THREAD

**Issue by bloody2k** [korylprince/hassio-node-red#8]
Hi,

I'm trying to get SONOS and XIAOMI (mi-devices) nodes to work, but it can't find my devices.

In the xiaomi github I found one having trouble, and with the following solution.

> I had the same issue - I'm running Node-RED in a Docker container but my setup does not work with port mapping for UDP multicast. Instead of mapping only -p 1880:1880 i used --net=host when I started the container.
E.g.
> docker run -it --net=host --user 1026 -v /volume1/docker/nodered/:/data --name nodered pgnodered:1.0.1

Could it be a problem caused by this add-on which can be solved in any way?

/Stefan

**Comment by korylprince** [comment]
I've changed the add-on to use host networking (equivalent to the `--net=host`) in version 1.7.

If that doesn't fix the issue, re-open this issue and please provide some more info.
