### ISSUE TITLE
这个版本的node-red如何安装homekit？

### ISSUE THREAD

**Issue by czweb** [korylprince/hassio-node-red#9]
请问作者在node-red里使用homekit吗？
这个安装不上呢？https://flows.nodered.org/node/node-red-contrib-homekit
```
apt-get install libavahi-compat-libdnssd-devcd 
npm install node-red-contrib-homekit
```
使用上面这2个命令装不上，就算临时装上了，重启node-red后homekit也会自动就没了，是为什么呢？
我在这里发过帖子，也没人知道https://bbs.hassbian.com/thread-2699-1-1.html

**Comment by korylprince** [comment]
This is a duplicate of #7. Please see my comments there.
